export type SearchItem = {
  title: string;
  href: string;
  section: string;
  description: string;
  keywords: string;
};

export const searchIndex: SearchItem[] = [
  {
    title: 'Home',
    href: '/',
    section: 'Overview',
    description: 'Best Democracy overview, election reform problems, remedies, and calls to action.',
    keywords: 'inclusive democracy proportional representation colorado election reform home rule fair elections remedies',
  },
  {
    title: 'At-Large Elections',
    href: '/at-large-elections',
    section: 'Understanding',
    description: 'At-Large Plurality, block voting, wasted votes, Boulder City Council, and discriminatory election design.',
    keywords: 'at large elections plurality block voting boulder plan boulder wasted votes dillard crenshaw charleston county',
  },
  {
    title: 'PLAN Boulder and Wasted Votes',
    href: '/at-large-elections',
    section: 'At-Large Elections',
    description: 'Boulder 2017 example: 48.5% of votes produced 80% of open seats and 100% of council power.',
    keywords: 'plan boulder pbc boulder city council 2017 48.5 80 100 wasted votes new urbanist spoiler effect renters students',
  },
  {
    title: 'Voting Rights Act and At-Large Plurality',
    href: '/at-large-elections',
    section: 'At-Large Elections',
    description: 'Court cases involving at-large elections, discrimination, block voting, and minority exclusion.',
    keywords: 'voting rights act at large plurality discrimination block voting dillard crenshaw brown board commissioners charleston county jones county',
  },
  {
    title: 'Electoral College',
    href: '/electoral-college',
    section: 'Understanding',
    description: 'The Electoral College, slavery, false majority government, swing states, and National Popular Vote.',
    keywords: 'electoral college slavery madison national popular vote false majority president swing states mcgovern',
  },
  {
    title: 'False Majority Government',
    href: '/electoral-college',
    section: 'Electoral College',
    description: 'Presidents can win the Electoral College while losing the popular vote.',
    keywords: 'false majority government popular vote electoral college swing states president losing popular vote',
  },
  {
    title: 'National Popular Vote',
    href: '/electoral-college',
    section: 'Electoral College',
    description: 'Action item: lobby state representatives to support the National Popular Vote.',
    keywords: 'national popular vote npv lobby state representatives electoral college reform one person one vote',
  },
  {
    title: 'Identifying Election Issues',
    href: '/identifying-issues',
    section: 'Understanding',
    description: 'The 12 methods used to control elections, suppress voters, and obstruct democracy.',
    keywords: 'voter suppression candidate suppression gerrymandering campaign finance courts cartel voting integrity',
  },
  {
    title: 'Dillon’s Rule and State Preemption',
    href: '/home-rule',
    section: 'Home Rule',
    description: 'State power over local governments can obstruct local election reform and grassroots democracy.',
    keywords: 'dillons rule dillon rule state preemption local government home rule charter counties cities obstruction',
  },
  {
    title: 'Good Governance Boards',
    href: '/direct-democracy',
    section: 'Direct Democracy',
    description: 'Independent local oversight can measure democratic quality and expose election-system problems.',
    keywords: 'good governance boards oversight democracy index local government accountability ethics',
  },
  {
    title: 'Single Transferable Vote',
    href: '/single-transferable-vote',
    section: 'Proportional Representation',
    description: 'STV in multi-member districts, ranked ballots, proportional outcomes, and low wasted votes.',
    keywords: 'single transferable vote stv ranked choice voting rcv multi member districts proportional representation boulder',
  },
  {
    title: 'Ranked Choice Voting vs STV',
    href: '/single-transferable-vote',
    section: 'Single Transferable Vote',
    description: 'Why single-winner RCV is not proportional and STV solves more representation problems.',
    keywords: 'ranked choice voting rcv instant runoff irv single transferable vote stv spoiler effect wasted votes transfers',
  },
  {
    title: 'Multi-Member Districts',
    href: '/single-transferable-vote',
    section: 'Single Transferable Vote',
    description: 'Multi-member districts make proportional representation possible and reduce wasted votes.',
    keywords: 'multi member districts seven seats district proportional representation geographic distribution minority representation',
  },
  {
    title: 'Hybrid Proportional Representation',
    href: '/hybrid-proportional-representation',
    section: 'Proportional Representation',
    description: 'Hybrid Pro Rep system design combining local districts, leveling seats, and proportional outcomes.',
    keywords: 'hybrid proportional representation hpr leveling seats best losers districts colorado parliament',
  },
  {
    title: 'Mixed Member Proportional',
    href: '/mixed-member-proportional',
    section: 'Proportional Representation',
    description: 'MMP systems, district seats, party list seats, and proportional legislatures.',
    keywords: 'mixed member proportional mmp new zealand germany party list district seats proportional',
  },
  {
    title: 'Party List',
    href: '/party-list',
    section: 'Proportional Representation',
    description: 'Party List proportional representation and how it compares to US winner-take-all elections.',
    keywords: 'party list proportional representation parties parliament wasted votes netherlands denmark',
  },
  {
    title: 'Home Rule',
    href: '/home-rule',
    section: 'Remedies',
    description: 'Home Rule, local self-determination, county charters, ballot initiatives, and Colorado local power.',
    keywords: 'home rule colorado counties charter local government direct democracy ballot initiatives dillons rule',
  },
  {
    title: 'Colorado County Home Rule',
    href: '/home-rule',
    section: 'Home Rule',
    description: 'Home Rule lets local governments write charters and change local democratic structures.',
    keywords: 'colorado counties statutory home rule charter county commissioners direct democracy ballot initiatives pitkin weld denver broomfield',
  },
  {
    title: 'Abolish the Senate',
    href: '/abolish-senate',
    section: 'Remedies',
    description: 'Senate distortions, minority rule, proxy voting, and reform or abolition options.',
    keywords: 'abolish senate filibuster wyoming california minority rule proxy voting unicameral',
  },
  {
    title: 'Direct Democracy',
    href: '/direct-democracy',
    section: 'Remedies',
    description: 'Ballot initiatives, online petition gathering, Boulder Measure 2G, and Evan Ravitz.',
    keywords: 'direct democracy ballot initiatives electronic petitions online petition gathering evan ravitz measure 2g',
  },
  {
    title: 'Boulder Ballot Measure 2G',
    href: '/direct-democracy',
    section: 'Direct Democracy',
    description: 'Boulder voters approved online petition gathering measure 2G in 2018.',
    keywords: 'boulder ballot measure 2g question 2g online petition gathering evan ravitz obstruction electronic petitions',
  },
  {
    title: 'Electronic Petition Gathering',
    href: '/direct-democracy',
    section: 'Direct Democracy',
    description: 'Digital petitions can be signed online, reduce paid-petitioner problems, and improve access.',
    keywords: 'electronic ballot initiatives digital petitions online petitions eSign go vote colorado secretary of state oregon citizen initiative review',
  },
  {
    title: 'Democratize the Supreme Court',
    href: '/democratize-supreme-court',
    section: 'Remedies',
    description: 'Court reform, lifetime appointments, ethics rules, minority rule, and democratic legitimacy.',
    keywords: 'supreme court court reform term limits ethics citizens united dred scott minority rule',
  },
  {
    title: 'Supreme Court Term Limits and Ethics',
    href: '/democratize-supreme-court',
    section: 'Democratize the Supreme Court',
    description: 'Court reform options include fixed terms, regularized appointments, ethics rules, and recusal standards.',
    keywords: 'supreme court term limits ethics recusal court packing lifetime appointments judicial reform accountability',
  },
  {
    title: 'Best Democracy Index',
    href: '/best-democracy-index',
    section: 'Resources',
    description: 'A framework for measuring representation, participation, accountability, and dispersed power.',
    keywords: 'best democracy index representation participation accountability dispersed power wasted votes proportionality',
  },
  {
    title: 'Court Cases',
    href: '/court-cases',
    section: 'Resources',
    description: 'Voting rights and democracy court cases from Somerset v. Stewart to Citizens United.',
    keywords: 'court cases somerset dred scott plessy reynolds dillard shelby citizens united buckley mccutcheon',
  },
  {
    title: 'Citizens United, Buckley, and McCutcheon',
    href: '/court-cases',
    section: 'Court Cases',
    description: 'Campaign finance cases that expanded money power in elections.',
    keywords: 'citizens united buckley valeo mccutcheon fec campaign finance money speech dark money corporations',
  },
  {
    title: 'Dred Scott, Plessy, and Shelby County',
    href: '/court-cases',
    section: 'Court Cases',
    description: 'Court cases tied to slavery, Jim Crow, voting rights, and democratic setbacks.',
    keywords: 'dred scott plessy ferguson shelby county holder voting rights act jim crow slavery supreme court',
  },
  {
    title: 'Somerset v. Stewart',
    href: '/court-cases',
    section: 'Court Cases',
    description: 'The 1772 case abolishing slavery in England and Wales.',
    keywords: 'somerset stewart lord mansfield slavery england wales american revolution',
  },
  {
    title: 'Slavery and US Elections',
    href: '/slavery-and-us-elections',
    section: 'Observation',
    description: 'How slavery shaped US election systems, the Constitution, and enduring electoral distortions.',
    keywords: 'slavery us elections somerset stewart constitutional convention madison three fifths compromise',
  },
  {
    title: 'Constitutional Convention and Slaver Strategy',
    href: '/slavery-and-us-elections',
    section: 'Slavery and US Elections',
    description: 'How Madison and slaveholding elites shaped constitutional election systems.',
    keywords: 'constitutional convention slaver strategy james madison virginia plan three fifths compromise article v electoral college senate',
  },
  {
    title: 'Events',
    href: '/events',
    section: 'Community',
    description: 'Best Democracy events, meetings, presentations, and local organizing.',
    keywords: 'events meetup meetings organizing presentations local virtual',
  },
  {
    title: 'Discussion Forum',
    href: '/blog',
    section: 'Community',
    description: 'Discussion forum for election reform, democracy, proportional representation, and organizing.',
    keywords: 'blog forum discussion posts comments election reform democracy community',
  },
  {
    title: 'About Jesse Kumin',
    href: '/about',
    section: 'About',
    description: 'About Jesse Kumin and the origin of Best Democracy.',
    keywords: 'about jesse kumin founder best democracy boulder colorado',
  },
  {
    title: 'Bylaws',
    href: '/bylaws',
    section: 'About',
    description: 'Best Democracy organizational governance and bylaws.',
    keywords: 'bylaws governance organization best democracy',
  },
  {
    title: 'Contact',
    href: '/contact',
    section: 'About',
    description: 'Contact Best Democracy with questions, ideas, resources, and organizing requests.',
    keywords: 'contact email message jesse best democracy',
  },
  {
    title: 'Privacy Policy',
    href: '/privacy',
    section: 'Policy',
    description: 'Privacy policy for account, newsletter, and contact data.',
    keywords: 'privacy policy data newsletter contact account',
  },
  {
    title: 'Accessibility',
    href: '/accessibility',
    section: 'Policy',
    description: 'Accessibility statement and feedback information.',
    keywords: 'accessibility wcag feedback barriers',
  },
];
